<?php
// echo 'controllers\we<br>';

/**
*
*/
class Member extends Controller
{
	public function index($params = null)
	{
		$model = $this->model('member_model');
		$MemberArrayUse = array($model->getFlagTitle(),
								$model->getFlagChildrenTitle(),
								$model->getCharacterImage(),
								$model->getCharacterName(),
								$model->getCharacterBirthday(),
								$model->getCharacterJob(),
								$model->getCharacterContentParagraphOne(),
								$model->getCharacterContentParagraphTwo(),
								$model->getFlagChildrenTitleChange());
		$this->view('layouts/peoplelist',
			array('LeaderBA' => $MemberArrayUse[0][0],
				  'CoreBA' => $MemberArrayUse[0][1],
				  'WorkTeamBA' => $MemberArrayUse[0][2],
				  'GeniusCat' => $MemberArrayUse[1][0],
				  'OslandWen' => $MemberArrayUse[1][1],
				  'DouKaLuCha' => $MemberArrayUse[1][2],
				  'BinzuOtoto' => $MemberArrayUse[1][3],
				  'NekoOtoto' => $MemberArrayUse[1][4],
				  'BokeNeko' => $MemberArrayUse[1][5],
				  'KaiKai' => $MemberArrayUse[1][6],
				  'RokuBan' => $MemberArrayUse[1][7],
				  'MizuNoShinku' => $MemberArrayUse[1][8],
				  'GoNeko' => $MemberArrayUse[1][9],
				  'Purachina' => $MemberArrayUse[1][10],
				  'JoshiKousei' => $MemberArrayUse[1][11],
				  'Murasaki' => $MemberArrayUse[1][12],
				  'ShainNaito' => $MemberArrayUse[1][13],
				  'ShiroiFeza' => $MemberArrayUse[1][14],
				  'purple' => $MemberArrayUse[2][0],
				  'purple' => $MemberArrayUse[2][1],
				  'purple' => $MemberArrayUse[2][2],
				  'purple' => $MemberArrayUse[2][3],
				  'purple' => $MemberArrayUse[2][4],
				  'purple' => $MemberArrayUse[2][5],
				  'purple' => $MemberArrayUse[2][6],
				  'purple' => $MemberArrayUse[2][7],
				  'purple' => $MemberArrayUse[2][8],
				  'purple' => $MemberArrayUse[2][9],
				  'purple' => $MemberArrayUse[2][10],
				  'purple' => $MemberArrayUse[2][11],
				  'purple' => $MemberArrayUse[2][12],
				  'purple' => $MemberArrayUse[2][13],
				  'purple' => $MemberArrayUse[2][14],
				  'Character1N' => $MemberArrayUse[3][0],
				  'Character1B' => $MemberArrayUse[4][0],
				  'Character1J' => $MemberArrayUse[5][0],
				  'Character1P1' => $MemberArrayUse[6][0],
				  'Character1P2' => $MemberArrayUse[7][0],
				  'Character2N' => $MemberArrayUse[3][1],
				  'Character2B' => $MemberArrayUse[4][1],
				  'Character2J' => $MemberArrayUse[5][1],
				  'Character2P1' => $MemberArrayUse[6][1],
				  'Character2P2' => $MemberArrayUse[7][1],
				  'Character3N' => $MemberArrayUse[3][2],
				  'Character3B' => $MemberArrayUse[4][2],
				  'Character3J' => $MemberArrayUse[5][2],
				  'Character3P1' => $MemberArrayUse[6][2],
				  'Character3P2' => $MemberArrayUse[7][2],
				  'Character4N' => $MemberArrayUse[3][3],
				  'Character4B' => $MemberArrayUse[4][3],
				  'Character4J' => $MemberArrayUse[5][3],
				  'Character4P1' => $MemberArrayUse[6][3],
				  'Character4P2' => $MemberArrayUse[7][3],
				  'Character5N' => $MemberArrayUse[3][4],
				  'Character5B' => $MemberArrayUse[4][4],
				  'Character5J' => $MemberArrayUse[5][4],
				  'Character5P1' => $MemberArrayUse[6][4],
				  'Character5P2' => $MemberArrayUse[7][4],
				  'Character6N' => $MemberArrayUse[3][5],
				  'Character6B' => $MemberArrayUse[4][5],
				  'Character6J' => $MemberArrayUse[5][5],
				  'Character6P1' => $MemberArrayUse[6][5],
				  'Character6P2' => $MemberArrayUse[7][5],
				  'Character7N' => $MemberArrayUse[3][6],
				  'Character7B' => $MemberArrayUse[4][6],
				  'Character7J' => $MemberArrayUse[5][6],
				  'Character7P1' => $MemberArrayUse[6][6],
				  'Character7P2' => $MemberArrayUse[7][6],
				  'Character8N' => $MemberArrayUse[3][7],
				  'Character8B' => $MemberArrayUse[4][7],
				  'Character8J' => $MemberArrayUse[5][7],
				  'Character8P1' => $MemberArrayUse[6][7],
				  'Character8P2' => $MemberArrayUse[7][7],
				  'Character9N' => $MemberArrayUse[3][8],
				  'Character9B' => $MemberArrayUse[4][8],
				  'Character9J' => $MemberArrayUse[5][8],
				  'Character9P1' => $MemberArrayUse[6][8],
				  'Character9P2' => $MemberArrayUse[7][8],
				  'Character10N' => $MemberArrayUse[3][9],
				  'Character10B' => $MemberArrayUse[4][9],
				  'Character10J' => $MemberArrayUse[5][9],
				  'Character10P1' => $MemberArrayUse[6][9],
				  'Character10P2' => $MemberArrayUse[7][9],
				  'Character11N' => $MemberArrayUse[3][10],
				  'Character11B' => $MemberArrayUse[4][10],
				  'Character11J' => $MemberArrayUse[5][10],
				  'Character11P1' => $MemberArrayUse[6][10],
				  'Character11P2' => $MemberArrayUse[7][10],
				  'Character12N' => $MemberArrayUse[3][11],
				  'Character12B' => $MemberArrayUse[4][11],
				  'Character12J' => $MemberArrayUse[5][11],
				  'Character12P1' => $MemberArrayUse[6][11],
				  'Character12P2' => $MemberArrayUse[7][11],
				  'Character13N' => $MemberArrayUse[3][12],
				  'Character13B' => $MemberArrayUse[4][12],
				  'Character13J' => $MemberArrayUse[5][12],
				  'Character13P1' => $MemberArrayUse[6][12],
				  'Character13P2' => $MemberArrayUse[7][12],
				  'Character14N' => $MemberArrayUse[3][13],
				  'Character14B' => $MemberArrayUse[4][13],
				  'Character14J' => $MemberArrayUse[5][13],
				  'Character14P1' => $MemberArrayUse[6][13],
				  'Character14P2' => $MemberArrayUse[7][13],
				  'Character15N' => $MemberArrayUse[3][14],
				  'Character15B' => $MemberArrayUse[4][14],
				  'Character15J' => $MemberArrayUse[5][14],
				  'Character15P1' => $MemberArrayUse[6][14],
				  'Character15P2' => $MemberArrayUse[7][14],

				  'ChildrenTitleChange5' => $MemberArrayUse[8][5],
				  'ChildrenTitleChange6' => $MemberArrayUse[8][6]
				  ));
	}
}







